name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black
  - click
  - fire
  - funcy
  - h5py
  - ipython
  - jupyter
  - matplotlib
  - mypy
  - numba
  - numpy
  - opencv
  # - opend3d
  - pandas
  # - pip
  # - pylops==1.18.3
  - py-spy
  - pyntcloud
  - pyyaml
  - scikit-video
  - scipy
  - seaborn
  - tk

